name: CI/CD Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Test Python File
        run: |
          python -m py_compile app.py

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-flask-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-flask-app:latest

      - name: Deploy Locally Using Docker Compose
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          docker compose down || true
          docker compose pull
          docker compose up -d
